---
title: "2020-02-26-MADdataviz"
author: "Rayna M Harris"
date: "2/17/2020"
output: md_document
---

# Customizing plots with colors and themes

## For Meet and Analyze Data, February 26, 2020

```{r setup}
library(tidyverse)
library(cowplot)
knitr::opts_chunk$set(echo = TRUE, fig.path = "./images/")
```


```{r cars}
# view data
head(mpg)
summary(mpg)

## start with basic plot
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy))

## color by factors, default
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy, color = as.factor(cyl)))
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy, color = as.factor(class)))

## specify order
levelscyl <- c("4", "5", "6",  "8" )
levelsclass <- c("2seater", "subcompact", "compact", "midsize",
                 "suv", "minivan", "pickup")
mpg$cyl <- factor(mpg$cyl, levels = levelscyl)
mpg$class <- factor(mpg$class, levels = levelsclass)

## pick colors using http://colorbrewer2.org/
colorscyl <- c("4" = "#fdcc8a", 
               "5" = "#fc8d59", 
               "6" = "#e34a33",
               "8" = "#b30000")

colorsclass <- c("2seater" = "#e41a1c", 
                 "subcompact" = "#1b7837", 
                 "compact" = "#7fbf7b", "midsize" = "#d9f0d3",
                 "suv" = "#d8b365", 
                 "minivan" = "#dfc27d", "pickup" = "#bf812d")

colorsall <- c(colorscyl, colorsclass)

ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy, color = cyl)) +
  scale_color_manual(values = colorsall)
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy, color = class)) +
    scale_color_manual(values = colorsall)

## add a custom theme

mytheme <- function(){
  theme_classic() +
    theme(legend.position = "bottom",
          axis.text.y = element_text(face = "italic"),
          axis.text.x = element_text(angle = 45, hjust = 1))
}

a <- ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy, color = cyl)) +
    scale_color_manual(values = colorsall)  +
  mytheme()  
a

b <- ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy, color = class)) +
    scale_color_manual(values = colorsall)  +
  mytheme()
b

c <- ggplot(mpg, aes(x = cyl, y = hwy, fill = cyl)) + 
  geom_boxplot(mapping = aes(x = cyl, y = hwy, fill = cyl)) +
    scale_fill_manual(values = colorsall)  +
  mytheme()  
c

d <- ggplot(data = mpg) + 
  geom_boxplot(mapping = aes(x = class, y = hwy, fill = class)) +
    scale_fill_manual(values = colorsall)  +
  mytheme()
d

# plot together badly
plot_grid(a,b,c,d)

# plot together better
plot_grid(a,b,
          c + theme(legend.position = "none" ),
          d + theme(legend.position = "none"),
          rel_heights = c(0.55,0.45),
          label_size = 12, labels = "auto")

```

