name: Onboard new member checklist
description: Create an issue to onboad a new member
title: "[Onboarding: Member] "
labels: ["onboarding"]
assignees:
  - ACharbonneau 
body:
  - type: markdown
    attributes:
      value: |
        # Onboarding Checklist
